Fix TypeError when checking token
NiceAesth/aiosu pull request #142
Opened 2023-05-01 17:43 UTC by Kuro-Rui

## Self-check

- [ ] The changes are tested with [pre-commit](https://pre-commit.com/)
- [ ] The changes pass unit testing with [pytest](https://pre-commit.com/)
- [ ] The changes pass [mypy](http://mypy-lang.org/)

2023-05-15 14:46 UTC, NiceAesth commented
Have been a bit busy, apologies for not responding to this PR yet. Will take a look at it later today

2023-05-15 14:51 UTC, NiceAesth commented
Could you provide a stack trace / reproduction steps until then?

2023-05-16 13:17 UTC, NiceAesth requested changes

2023-05-16 13:17 UTC, NiceAesth commented on aiosu/v2/client.py
> +        try:
```suggestion
        if datetime.now(tz=timezone.utc) > token.expires_on:
```

2023-05-16 13:17 UTC, NiceAesth commented on aiosu/v2/client.py
> +        try:
if this change is needed (not sure why you were getting typeerror from this), a try except is a poor way to handle it. just pass the timezone info always

2023-05-16 13:18 UTC, NiceAesth commented on aiosu/v2/client.py
> +        try:
i assume this is from passing a date object when creating the token. can just switch this function from a naive dt check

2023-05-17 18:18 UTC, NiceAesth commented
ah, that is a bit annoying. would like reproduction steps to see if this is worth investigating further

2023-05-20 14:56 UTC, Kuro-Rui commented
Sorry, been abandoning this for a while...
The new changes look great actually, I didn't think of using timestamp instead :p

2023-05-20 14:58 UTC, Kuro-Rui commented
> ah, that is a bit annoying. would like reproduction steps to see if this is worth investigating further

I don't really know how to reproduce, but sometimes the datetime  object has a tz, so it returns a TypeError when checked with a datetime.utcnow() which has no tz.

2023-05-20 22:08 UTC, NiceAesth approved these changes
looks fine

2023-05-20 22:08 UTC, merged