Changed: event.py Fixed typo errors in Event(BaseModel) achievement: …
NiceAesth/aiosu pull request #164
Opened 2023-08-24 20:01 UTC by EnricoBaivo

…Optional[Achievement] = None # typo achievment  and in common.py Achievement(BaseModel) description: str # typo desciption

## Self-check

- [ ] The changes are tested with [pre-commit](https://pre-commit.com/)
- [ ] The changes pass unit testing with [pytest](https://pre-commit.com/)
- [ ] The changes pass [mypy](http://mypy-lang.org/)

2023-08-24 22:51 UTC, NiceAesth requested changes

2023-08-24 22:51 UTC, NiceAesth commented on aiosu/models/event.py
> +    achievement: Optional[Achievement] = None  # typo achievment
Please do not add comments like these to the code

2023-08-24 22:51 UTC, NiceAesth commented on aiosu/models/common.py
> +    description: str  # typo  desciption
Same as above

2023-08-24 22:51 UTC, NiceAesth commented on .pre-commit-config.yaml
> +    python: python3.11
Do not do unrelated changes in prs

2023-08-24 22:51 UTC, NiceAesth commented on .gitignore
> +.gitigonre
Do not do unrelated changes in prs

2023-08-24 22:52 UTC, NiceAesth commented
Could be worth cross checking types with osu-web. https://github.com/ppy/osu-web/tree/master/app/Models

2023-08-25 13:48 UTC, NiceAesth approved these changes

2023-08-25 13:49 UTC, NiceAesth commented
I went ahead and fixed the issues myself. Read through the changes I have made in case you wish to see the direction to take PRs in the future.

(also, as a future note I recommend reading https://towardsdatascience.com/why-good-codes-dont-need-comments-92f58de19ad2)

2023-08-25 13:49 UTC, merged

2023-08-25 14:08 UTC, EnricoBaivo commented
Thanks alot for the informations, indeed it was my first pull request ever. So im looking forward to learn the correct patterns and rules for prs.