feat: update PP calculators for standard, catch and mania
NiceAesth/aiosu pull request #257
Opened 2024-12-04 19:43 UTC by minisbett

## Self-check

- [ ] The changes are tested with [pre-commit](https://pre-commit.com/)
- [ ] The changes pass unit testing with [pytest](https://pre-commit.com/)
- [ ] The changes pass [mypy](http://mypy-lang.org/)

2024-12-05 16:39 UTC, NiceAesth requested changes
writing this down but theres so many typing things that i will just look at this in the weekend

2024-12-05 16:39 UTC, NiceAesth commented on aiosu/utils/performance.py
> +    def _is_slider_head_accuracy(self, Score) -> bool:
```suggestion
    def _is_slider_head_accuracy(self, score: Score) -> bool:
```

2024-12-05 16:39 UTC, NiceAesth commented on aiosu/utils/performance.py
> +                    effective_miss_count = full_combo_threshold / max(
```suggestion
                    effective_miss_count = full_combo_threshold // max(
```

not sure if this is right though?

2024-12-05 16:39 UTC, NiceAesth commented on aiosu/utils/performance.py
> +                    effective_miss_count = full_combo_threshold / max(
```suggestion
                    effective_miss_count = full_combo_threshold // max(
```

2024-12-08 17:13 UTC, minisbett commented on aiosu/utils/performance.py
> +                    effective_miss_count = full_combo_threshold / max(
effective misscount is a decimal number

2024-12-08 17:14 UTC, minisbett commented on aiosu/utils/performance.py
> +                    effective_miss_count = full_combo_threshold / max(
nop

2025-03-12 20:56 UTC, NiceAesth approved these changes
passes tests now

2025-03-12 20:57 UTC, merged